### ISSUE TITLE
listFunctions 不存在

### ISSUE THREAD

**Issue by wanglong167** [TencentCloudBase/cloudbase-manager-node#1]
let res = await functions.listFunctions(20, 0)

查看源码是

await functions.listFunction(20, 0)

文档多了个s

**Comment by Mrjing** [comment]
嗯， 这个地方文档有误，我们会更正

**Comment by wanglong167** [comment]
不过我看 scf 叫的是ListFunctions   
有强迫症 你们没对齐。。。

**Comment by Mrjing** [comment]
嗯，代码里确实未对齐好，这里应该对齐为listFunctions
