### ISSUE TITLE
停用用户以后没有启用用户的选择

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-manager-node#11]
增加启用用户的选项

**Comment by Mrjing** [comment]
这里可以再描述详细一些吗

**Comment by juukee** [comment]
https://docs.cloudbase.net/api-reference/manager/node/user.html#pi-liang-shan-chu-yong-hu

只有停用用户，没有启用用户。。

**Comment by Mrjing** [comment]
嗯，目前的接口只有停用用户接口

**Comment by juukee** [comment]
实际上都是把这个用户的Status更新值。理论上需要启用用户，防止禁用以后无法重新启用

**Comment by Mrjing** [comment]
嗯，这里的需求我们看一下是否可以满足

**Comment by juukee** [comment]
IsDisabled: false,   改成这个就行了·
