### ISSUE TITLE
envId这个是默认必须值，必须要传

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-manager-node#13]
envId这个是默认必须值，必须要传，如果没有会报错，而文档介绍写的是不填使用默认环境，这一步待确认，我测试了是必须传这个envId

**Comment by chhpt** [comment]
@juukee 请问是从哪里的文档看到的呢？

**Comment by juukee** [comment]
https://docs.cloudbase.net/api-reference/manager/node/initialization.html

**Comment by juukee** [comment]
看来是我理解错了。
