### ISSUE TITLE
test files error 

### ISSUE THREAD

**Issue by juukee** [TencentCloudBase/cloudbase-manager-node#14]
```js
npm run test 
```
TSError: TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
test/global-setup-hook.ts:1:33 - error TS2307: Cannot find module './config' or its corresponding type declarations.

1 import { cloudBaseConfig } from './config'
config file is not exits

**Comment by chhpt** [comment]
本地测试需要手动添加 config 文件
