### ISSUE TITLE
无法在nestjs中使用

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-manager-node#31]
重现步骤
```
nest new tcb-test
yarn add @cloudbase/node-sdk
yarn add @cloudbase/manager-node

//main.ts
import CloudBase from '@cloudbase/manager-node';
import tcb from '@cloudbase/node-sdk';
console.log('tcb:', tcb);
console.log('CloudBase:', CloudBase);

//输出
// tcb: undefined
// CloudBase: undefined
```
![image](https://user-images.githubusercontent.com/80653/157200114-dbedb505-4e5b-45f4-9673-b688fd25a16c.png)
![image](https://user-images.githubusercontent.com/80653/157200463-a51460b5-6ccb-44ac-94b9-181ee552e55e.png)

**Comment by DaZiYuan** [comment]
[tcb-nest-test.zip](https://github.com/TencentCloudBase/cloudbase-manager-node/files/8204258/tcb-nest-test.zip)

**Comment by juukee** [comment]
```
import CloudBase = require("@cloudbase/manager-node");
```

**Comment by DaZiYuan** [comment]
require 可以，官方还是支持一下标准写法吧

**Comment by juukee** [comment]
![1648179241](https://user-images.githubusercontent.com/28680837/160048994-835b7e95-c33a-49a5-8709-e507bd28e27c.png)
我在非nestjs框架里面又可以运行官方文档示例...

**Comment by juukee** [comment]
![1648179367(1)](https://user-images.githubusercontent.com/28680837/160049176-8a9b47f6-ab05-40bf-bdf2-78f33727cf16.png)
我在非nestjs框架里面又可以运行官方示例代码...

**Comment by DaZiYuan** [comment]
nest 确实不行，等戴佬出来讲讲吧

**Comment by juukee** [comment]
# tsconfig.json
"esModuleInterop": true, 

加一条这个设置解决问题

**Comment by DaZiYuan** [comment]
> # tsconfig.json
> "esModuleInterop": true,
> 
> 加一条这个设置解决问题

666
