### ISSUE TITLE
通过 CreatePostpayPackage 无法创建后付费，显示如下错误

### ISSUE THREAD

**Issue by lihengdao** [TencentCloudBase/cloudbase-manager-node#8]
状态检查失败，请检查环境状态是否正常，包括但不限于：环境未创建，环境未初始化完成，资源创建或者变更中，超出操作次数限制

**Comment by chhpt** [comment]
@lihengdao 请提供详细的报错信息哈

**Comment by lihengdao** [comment]
"{"Response":{"Error":{"Code":"InvalidParameter","Message":"状态检查失败，请检查环境状态是否正常，包括但不限于：环境未创建，环境未初始化完成，资源创建或者变更中，超出操作次数限制"},"RequestId":"81583b8f-e67f-4b92-a9f7-6a511ee64442"}}"
