### ISSUE TITLE
[Q]请问这个库和 你们的 tcb-admin-node这个，功能看上去是一样的么？是在重复造轮子么？

### ISSUE THREAD

**Issue by sonofmagic** [TencentCloudBase/cloudbase-manager-node#9]
麻烦解答一下

**Comment by dongyuanxin** [comment]
## 功能定位

tcb-admin-node 是在服务端提供开发者**调用tcb服务的能力**

manager-sdk 提供给开发者**管理tcb服务的能力**，理论上控制台支持的操作，manager-sdk都支持。

## 底层数据

通过源码可以发现，tcb-admin-node 调用的是数据流接口，manager-sdk 调用的是云API接口

另外，tcb-admin-node 不再加新功能，请使用新版本：`@cloudbase/node-sdk`
